---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: paul2029
    group_name: devops
  vars_files:
    - variables.yml

  tasks:
    - name: Check the time
      command: dateagrekbdr
#      when: ansible_distribution == "paul" or ansible_processor_nproc == 2
    - name: create user paul
      user:
         name: "{{user_name}}"
         comment: Paul Admin
    - name: create group
      group:
         name: "{{group_name}}"
         state: present
      become: true
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present    


 